import { AuthType } from "./stores/auth.store";
import { PostType } from "./stores/post.store";

export const user: AuthType = {
  _id: "cacas1413",
  name: "Tran Trung Nghia",
  avatarUrl:
    "https://abs.twimg.com/sticky/default_profile_images/default_profile_bigger.png",
  username: "Tr_TrungNghia",
};
export const MOCK_USERS: AuthType[] = [
  {
    _id: "u1",
    name: "Nghĩa Trần",
    username: "nghiadev",
    avatarUrl: "https://i.pravatar.cc/150?img=1",
  },
  {
    _id: "u2",
    name: "Phương Lê",
    username: "phuongle",
    avatarUrl: "https://i.pravatar.cc/150?img=2",
  },
  {
    _id: "u3",
    name: "Lâm Dev",
    username: "lamadev",
    avatarUrl: "https://i.pravatar.cc/150?img=3",
  },
];
export const MOCK_POSTS: PostType[] = [
  {
    id: "p1",
    author: MOCK_USERS[0],
    context: "Just finished building my first Next.js App Router project 🚀",
    mediaUrl: "",
    totalComments: 12,
    totalShares: 4,
    totalFavorites: 31,
  },
  {
    id: "p2",
    author: MOCK_USERS[1],
    context: "Dark mode + shadcn/ui is such a clean combo 🖤",
    mediaUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475",
    totalComments: 8,
    totalShares: 2,
    totalFavorites: 19,
  },
  {
    id: "p3",
    author: MOCK_USERS[2],
    context: "Debugging until 2AM hits different 😵‍💫",
    mediaUrl: "",
    totalComments: 15,
    totalShares: 6,
    totalFavorites: 42,
  },
  {
    id: "p4",
    author: MOCK_USERS[0],
    context: "Zustand > Redux for most small to medium apps. Change my mind.",
    mediaUrl: "",
    totalComments: 22,
    totalShares: 10,
    totalFavorites: 58,
  },
  {
    id: "p5",
    author: MOCK_USERS[1],
    context: "Map-based apps are way more fun than CRUD dashboards 🗺️",
    mediaUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    totalComments: 11,
    totalShares: 3,
    totalFavorites: 27,
  },
  {
    id: "p6",
    author: MOCK_USERS[2],
    context: "If it works… don’t touch it. If it doesn’t… blame CORS 😅",
    mediaUrl: "",
    totalComments: 18,
    totalShares: 7,
    totalFavorites: 49,
  },
  {
    id: "p7",
    author: MOCK_USERS[0],
    context: "Clerk + Prisma + Postgres is a solid auth stack 🔐",
    mediaUrl: "",
    totalComments: 9,
    totalShares: 2,
    totalFavorites: 21,
  },
  {
    id: "p8",
    author: MOCK_USERS[1],
    context: "Anyone else love building side projects more than using them?",
    mediaUrl: "",
    totalComments: 14,
    totalShares: 5,
    totalFavorites: 33,
  },
  {
    id: "p9",
    author: MOCK_USERS[2],
    context: "Infinite scroll is easy until performance says hello 👋",
    mediaUrl: "",
    totalComments: 20,
    totalShares: 8,
    totalFavorites: 44,
  },
  {
    id: "p10",
    author: MOCK_USERS[0],
    context: "Thinking about turning my map app into a social platform 🤔",
    mediaUrl: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    totalComments: 17,
    totalShares: 6,
    totalFavorites: 39,
  },
  {
    id: "p11",
    author: MOCK_USERS[1],
    context: "Hot take: most apps don’t need microservices at all.",
    mediaUrl: "",
    totalComments: 26,
    totalShares: 12,
    totalFavorites: 61,
  },
  {
    id: "p12",
    author: MOCK_USERS[2],
    context: "When the hydration error disappears after a full reload 😌",
    mediaUrl: "",
    totalComments: 7,
    totalShares: 1,
    totalFavorites: 16,
  },
  {
    id: "p13",
    author: MOCK_USERS[0],
    context: "Spent more time naming variables than writing logic today.",
    mediaUrl: "",
    totalComments: 13,
    totalShares: 4,
    totalFavorites: 28,
  },
  {
    id: "p14",
    author: MOCK_USERS[1],
    context: "Side projects are the best way to learn real-world problems 💡",
    mediaUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    totalComments: 10,
    totalShares: 3,
    totalFavorites: 25,
  },
  {
    id: "p15",
    author: MOCK_USERS[2],
    context: "Shipping something imperfect beats waiting forever 🚢",
    mediaUrl: "",
    totalComments: 19,
    totalShares: 9,
    totalFavorites: 47,
  },
];
